FROM php:8.2-fpm

WORKDIR /var/www/HTML

# 必要なパッケージをインストール
RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    vim \
    zsh \
    unzip \
    libzip-dev \
    && docker-php-ext-install zip pdo pdo_mysql

# Node.jsとnpmのインストール
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs

# PHP 拡張モジュールのインストール
RUN docker-php-ext-install bcmath zip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Composerをインストール
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# zsh をデフォルトシェルに設定
RUN chsh -s $(which zsh)

# コンテナ起動時の作業ディレクトリを指定
WORKDIR /var/www/html