services:
  # PHP (Laravel) サービス
  app:
    container_name: ${APP_NAME}
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "8081:${WEB_PORT}"
    command: bash -c "mkdir -p /var/www/html/storage/logs /var/www/html/storage/framework/views && chown -R www-data:www-data /var/www/html/storage && php-fpm"

  web:
    container_name: ${WEB_NAME}
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - '${WEB_PORT}:80'
    depends_on:
      - app
